#!/bin/bash

source $EMB_LINUX_SCRIPTDIR_PATH/common/load_cfg.sh
source $EMB_LINUX_SCRIPTDIR_PATH/common/tty_screen.sh
source $EMB_LINUX_SCRIPTDIR_PATH/common/ip.sh

SCP_CMD="scp *.ko $SSH_REMOTE_USER@$ETH_REMOTE_ADDR:/$REMOTE_MOD_PATH"

if [ ! -z "$SSH_REMOTE_PASSWORD" ]; then
    sshpass -p $SSH_REMOTE_PASSWORD $SCP_CMD
else
    $SCP_CMD
fi
