#!/bin/bash

source $EMB_LINUX_SCRIPTDIR_PATH/common/load_cfg.sh
source $EMB_LINUX_SCRIPTDIR_PATH/common/tty_screen.sh
source $EMB_LINUX_SCRIPTDIR_PATH/common/ip.sh
$EMB_LINUX_SCRIPTDIR_PATH/common/tftp_server.sh
# bha, maybe someone, somewhere, will need somewhat like this..
# ..or probably something better than this crap..
sleep 0.2

if [ $# != 1 ]; then
    if [ $# != 3 ]; then
	echo "usage:"
	echo "$0 [<Kimage> <dtb>]"

	exit -1
    fi

    IMAGE=$2
    DTB=$3
else
    IMAGE=arch/$ARCH/boot/$KERNEL_IMAGE
    DTB=arch/$ARCH/boot/dts/$DTB_FILE
fi


UBOOT=$EMB_LINUX_SCRIPTDIR_PATH/common/uboot_put.sh

UBOOT_INIT_TFTP="setenv ipaddr $ETH_REMOTE_ADDR"
UBOOT_INIT_TFTP2="setenv serverip $ETH_LOCAL_ADDR"
UBOOT_LOAD_IMAGE="tftpboot $UBOOT_IMAGE_LOADADDR $ETH_LOCAL_ADDR:$IMAGE"

if [ -z "$DTB_FILE" ] ; then
    UBOOT_BOOTSTRAP="$BOOT_CMD $UBOOT_IMAGE_LOADADDR"
    UBOOT_LOAD_DTB=""
else
    UBOOT_LOAD_DTB="tftpboot $UBOOT_DTB_LOADADDR $ETH_LOCAL_ADDR:$DTB"
    UBOOT_BOOTSTRAP="$BOOT_CMD $UBOOT_IMAGE_LOADADDR - $UBOOT_DTB_LOADADDR"
fi

$UBOOT "$UBOOT_PRE_CMD;$UBOOT_INIT_TFTP;$UBOOT_INIT_TFTP2;$UBOOT_LOAD_DTB;$UBOOT_LOAD_IMAGE;$UBOOT_BOOTSTRAP"
