#!/bin/bash

source $EMB_LINUX_SCRIPTDIR_PATH/common/load_cfg.sh
source $EMB_LINUX_SCRIPTDIR_PATH/common/tty_screen.sh
source $EMB_LINUX_SCRIPTDIR_PATH/common/ip.sh

if [ $# -ge 2 ]; then
    KOS=""
    for KO in "$@"
    do
	KOS="$KOS `find -name $KO.ko`"
    done
else
    KOS=`find -name "*.ko"`
fi

echo "uploading:"
echo "$KOS"

SCP_CMD="scp -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no $KOS $SSH_REMOTE_USER@$ETH_REMOTE_ADDR:/$REMOTE_MOD_PATH"

if [ ! -z "$SSH_REMOTE_PASSWORD" ]; then
    sshpass -p $SSH_REMOTE_PASSWORD $SCP_CMD
else
    $SCP_CMD
fi
